### ISSUE TITLE
关于界面布局及优化

### ISSUE THREAD

**Issue by JianWenXie** [woaichunchunma/Lottery#1]
您好,我看你的demo写的非常好.只是几乎都没有注释,看的非常费劲.请问有空可以把注释补上去吗

**Comment by woaichunchunma** [comment]
嗯，有空我会补的，感谢使用，主页有Q群，可以加一下大家一起交流




发自网易邮箱大师
在2017年03月20日 14:21，JianWenXie 写道：

您好,我看你的demo写的非常好.只是几乎都没有注释,看的非常费劲.请问有空可以把注释补上去吗
